--- #YAML:1.0
name: Solaris-Disk-Mnttab
version: 0.01
author:
  - Jérôme Fenal <jfenal@free.fr>
abstract: ~
license: perl
requires:
  perl: 5.6.1
provides:
  Solaris::Disk::Mnttab:
    file: lib/Solaris/Disk/Mnttab.pm
    version: 0.01
generated_by: Module::Build version 0.25
