--- #YAML:1.0
name: Solaris-Disk-Mnttab
version: 0.02
author:
  - Jérôme Fenal <jfenal@free.fr>
abstract: Read Solaris list of mounted devices
license: perl
generated_by: Module::Build version 0.25, without YAML.pm
